version: '3.3'
services:
  customermicroserviceapi:
    build:
      context: /dotnetpublish/DemoMicroServiceProject/
      dockerfile: /dotnetpublish/DemoMicroServiceProject/Demo.MicroService.CustomerMicroService/Dockerfile
    image: customermicroserviceapi.v0315
    ports:
      - 5100:80/tcp
    container_name: "customermicroserviceapi"
    command: "dotnet /app/Demo.MicroService.CustomerMicroService.dll"
  usermicroserviceapi:
    build:
      context: /dotnetpublish/DemoMicroServiceProject/
      dockerfile: /dotnetpublish/DemoMicroServiceProject/Demo.MicroService.UserMicroservice/Dockerfile
    image: usermicroserviceapi.v0315
    ports:
      - 5200:80/tcp
    container_name: "usermicroserviceapi"
    command: "dotnet /app/Demo.MicroService.UserMicroservice.dll" 
  projectmicroserviceapi:
    build:
      context: /dotnetpublish/DemoMicroServiceProject/
      dockerfile: /dotnetpublish/DemoMicroServiceProject/Demo.MicroService.ProjectMicroService/Dockerfile
    image: projectmicroserviceapi.v0315
    ports:
      - 5300:80/tcp
    container_name: "projectmicroserviceapi"
    command: "dotnet /app/Demo.MicroService.ProjectMicroService.dll"
  authenticationcenter:
    build:
      context: /dotnetpublish/DemoMicroServiceProject/
      dockerfile: /dotnetpublish/DemoMicroServiceProject/Demo.MicroService.AuthenticationCenter/Dockerfile
    image: authenticationcenter.v0315
    ports:
      - 7200:80/tcp
    container_name: "authenticationcenter"
    command: "dotnet /app/Demo.MicroService.AuthenticationCenter.dll"
  gatewayapi:
    build:
      context: /dotnetpublish/DemoMicroServiceProject/
      dockerfile: /dotnetpublish/DemoMicroServiceProject/Demo.MicroService.GatewayCenter/Dockerfile
    image: gatewayapi.v0315
    ports:
      - 7200:80/tcp
    container_name: "gatewayapi"
    command: "dotnet /app/Demo.MicroService.GatewayCenter.dll"